### ISSUE TITLE
Removes manually uploaded or created files

### ISSUE THREAD

**Issue by ryanlovett** [data-8/nbpuller#41] opened 2017-04-24 17:05 UTC
A few students in stat28 and one in data8 have reported that files they create within their git repos get deleted. See https://piazza.com/class/ixxlkoprjq27g5.

I've no evidence that this is due to nbpuller and I haven't done any testing.

**Comment by SaladRaider** [comment] 2017-04-25 00:06
So far, it doesn't seem to be a nbpuller issue. I tried recreating the situation here: https://piazza.com/class/ixxlkoprjq27g5?cid=1216

I made a new folder called `investigation` in `data8assets/materials/sp17` and uploaded an ipynb there. I then hit a random nbpuller link like this one: `http://datahub.berkeley.edu/user-redirect/interact?repo=data8assets&path=materials/sp17/lab/lab02` and then checked to see if the new folder and notebook were there. both were.

I will try some more tests.

**Comment by ryanlovett** [comment] 2017-04-25 00:33
Thanks for checking. Can you try some variations? Like shutting down the server and then starting it up via /interact.

Could any of the git commands within nbpuller actually remove files?

**Comment by SaladRaider** [comment] 2017-04-25 01:01
git_cli.merge('-Xours', 'origin/' + branch)

**Comment by SaladRaider** [comment] 2017-04-28 21:58
I think I figured it out. The files that people upload to a git repo inside their notebooks will disappear when they run nbpuller and they change an existing file. Their files are not deleted, they are only hidden by spares checkout. The problem is, that nbpuller adds them to the repo and makes a commit to the manually uploaded files, but does not add them to the spares-checkout file.

**Comment by SaladRaider** [comment] 2017-05-03 20:47
@ryanlovett This is fixed now with the latest updates.

**Closed by SaladRaider** 2017-05-03 20:47 UTC

**Comment by ryanlovett** [comment] 2017-05-03 21:30
Great, thanks! Does your solution mean that people will see these old notebooks get "restored" vi the next checkout?

**Comment by SaladRaider** [comment] 2017-05-03 21:40
@ryanlovett no, it only adds their files to the sparse checkout if those files are newly added files, but this will probably not happen since git already committed their files.

They can restore them by using the terminal and running `echo "<file name>" >> .git/info/sparse-checkout` for each file they lost. And then run `git read-tree -m -u HEAD`.
